# commands that run after login to macOS user session
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# commands that run after AeroSpace startup
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# start AeroSpace at login
start-at-login = true

# normalizations: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

# 'main' binding mode declaration (must be present)
# see: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.main.binding]
ctrl-space = 'mode alt'

# see: https://nikitabobko.github.io/AeroSpace/commands#workspace
ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'

[mode.alt.binding]
space = 'mode main'
semicolon = ['reload-config', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
r = 'mode resize'
w = 'mode workspace'
t = 'mode tiling'
a = 'mode applications'

# moving: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
shift-1 = 'move-node-to-workspace 1'
shift-2 = 'move-node-to-workspace 2'
shift-3 = 'move-node-to-workspace 3'
shift-4 = 'move-node-to-workspace 4'
shift-5 = 'move-node-to-workspace 5'
shift-6 = 'move-node-to-workspace 6'
shift-7 = 'move-node-to-workspace 7'
shift-8 = 'move-node-to-workspace 8'
shift-9 = 'move-node-to-workspace 9'

# focusing: https://nikitabobko.github.io/AeroSpace/commands#focus
h = 'focus left'
j = 'focus down'
k = 'focus up'
l = 'focus right'

# moving: https://nikitabobko.github.io/AeroSpace/commands#move
shift-h = 'move left'
shift-j = 'move down'
shift-k = 'move up'
shift-l = 'move right'

# joining
ctrl-h = 'join-with left'
ctrl-j = 'join-with down'
ctrl-k = 'join-with up'
ctrl-l = 'join-with right'

[mode.resize.binding]
space = 'mode main'

# resizing: https://nikitabobko.github.io/AeroSpace/commands#resize
j = 'resize smart -50'
k = 'resize smart +50'

# rebalancing: https://nikitabobko.github.io/AeroSpace/commands#balance-sizes
equal = 'balance-sizes'

[mode.workspace.binding]
space = 'mode main'

# focusing: https://nikitabobko.github.io/AeroSpace/commands#focus-monitor
h = 'focus-monitor left'
j = 'focus-monitor down'
k = 'focus-monitor up'
l = 'focus-monitor right'

# moving: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-monitor
shift-h = ['move-node-to-monitor left', 'focus-monitor left']
shift-j = ['move-node-to-monitor down', 'focus-monitor down']
shift-k = ['move-node-to-monitor up', 'focus-monitor up']
shift-l = ['move-node-to-monitor right', 'focus-monitor right']

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
o = 'workspace prev'
i = 'workspace next'
shift-o = 'move-node-to-workspace prev'
shift-i = 'move-node-to-workspace next'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
shift-p = 'move-workspace-to-monitor prev'
shift-n = 'move-workspace-to-monitor next'

[mode.tiling.binding]
space = 'mode main'

# see: https://nikitabobko.github.io/AeroSpace/commands#flatten-workspace-tree
r = ['flatten-workspace-tree', 'mode main'] # reset layout

# see: https://nikitabobko.github.io/AeroSpace/commands#layout
f = ['layout floating tiling', 'mode main'] # toggle floating/tiling layout
t = ['layout tiles horizontal vertical', 'mode main']
a = ['layout accordion horizontal vertical', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

[mode.applications.binding]
space = 'mode main'

# exec: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
a = ['exec-and-forget open -a "Alacritty"', 'mode main']
s = ['exec-and-forget open -a "Firefox"', 'mode main']
d = ['exec-and-forget open -a "Discord"', 'mode main']
m = ['exec-and-forget open -a "Messages"', 'mode main']
l = ['exec-and-forget open -a "Slack"', 'mode main']
e = ['exec-and-forget open -a "Visual Studio Code"', 'mode main']
n = ['exec-and-forget open -a "Music"', 'mode main']
